import * as pdfjs from './vendor/pdf.mjs';
import {makeCurl,paintCurl,finishCurl} from './curl.js';
import {attachPageLinks} from './pdf-links.js';
import {preparePageSound,playPageSound} from './page-sound.js';
pdfjs.GlobalWorkerOptions.workerSrc = './vendor/pdf.worker.mjs';
const $=id=>document.getElementById(id);
let pdf=null,bytes=null,name='',pages=[],index=0,zoom=1,tab='pages',marks=[],generation=0,renderGeneration=0,busy=false,searchGeneration=0,thumbObserver;
const cache=new Map();
let wholeSources=new Set(),curl=null,gesture=null,suppressClickUntil=0;
function createCurl(direction){
 const sheet=makeCurl($('book'),direction,gesture?.y);if(!sheet)return null;curl=sheet;
 if(gesture){const next=pages[index+direction*count()];if(next)canvasFor(next,sheet.old.width).then(preview=>{if(curl!==sheet||!gesture)return;preview.className='curl-preview';preview.style.width=sheet.width+'px';preview.style.height=sheet.height+'px';preview.style.left=sheet.left+'px';sheet.preview=preview;sheet.old.style.visibility='hidden';$('book').insertBefore(preview,sheet.canvas)}).catch(()=>{});}
 return sheet;
}
const drawCurl=paintCurl;
async function settleCurl(sheet,target){await finishCurl(sheet,target,bookSound);sheet.old.style.visibility='';sheet.preview?.remove();if(curl===sheet)curl=null;}
const safeStore={get(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},set(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}};
const key=()=>`list:${pdf?.fingerprints[0]}`;
const count=()=>pages[index]?.half===null&&wholeSources.has(pages[index]?.source)?1:($('view').value==='double'&&innerWidth>760&&pages[index+1]?.half!==null?2:1);
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
function loading(on,text='Открываем книгу…'){$('loading').hidden=!on;$('loadingText').textContent=text}
function remember(){if(pdf)safeStore.set(key(),{index,marks,wholeSources:[...wholeSources]})}
function bookSound(){if($('sound').checked)playPageSound()}
async function openPDF(data,filename){const token=++generation;loading(true);try{const docTask=pdfjs.getDocument({data:data.slice(),cMapUrl:'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/cmaps/',cMapPacked:true,standardFontDataUrl:'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/standard_fonts/'});docTask.onPassword=(update,reason)=>{const password=prompt(reason===1?'Введите пароль PDF':'Неверный пароль. Попробуйте ещё раз');if(password===null)docTask.destroy();else update(password)};const doc=await docTask.promise;if(token!==generation){await doc.destroy();return}const previous=pdf;pdf=doc;bytes=data;name=filename;await previous?.destroy();cache.clear();index=0;const saved=safeStore.get(key(),{});marks=saved.marks||[];wholeSources=new Set(saved.wholeSources||[]);await rebuild();index=Math.min(saved.index||0,pages.length-1);$('title').textContent=name.replace(/\.pdf$/i,'');$('welcome').hidden=true;$('open').hidden=true;document.body.classList.add('reading');$('reader').hidden=false;$('navigation').hidden=false;$('progress').hidden=false;await render();await sidebar();}catch(error){console.error(error);toast('Не удалось открыть PDF. '+(error.name==='PasswordException'?'Нужен верный пароль.':'Проверьте, что файл не повреждён.'))}finally{if(token===generation)loading(false)}}
async function fileOpen(file){if(!file)return;if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){toast('Выберите файл PDF');return}await openPDF(new Uint8Array(await file.arrayBuffer()),file.name)}
async function rebuild(){if(!pdf)return;const token=generation,doc=pdf,mode=$('split').value;const next=[];for(let p=1;p<=doc.numPages;p++){const page=await doc.getPage(p);if(token!==generation)return;const v=page.getViewport({scale:1});const split=!wholeSources.has(p)&&(mode==='all'||mode==='auto'&&v.width/v.height>=1.2);for(let half=0;half<(split?2:1);half++)next.push({source:p,half:split?half:null,width:split?v.width/2:v.width,height:v.height})}pages=next;cache.clear();index=Math.min(index,pages.length-1);$('status').textContent=`PDF · ${pdf.numPages} листов · ${pages.length} страниц`;$('progress').max=pages.length-1;$('pageTotal').textContent=`/ ${pages.length}`;marks=marks.filter(m=>m<pages.length)}
async function canvasFor(entry,width){const scale=width/entry.width;const cacheKey=`${entry.source}:${entry.half}:${Math.round(width)}`;if(cache.has(cacheKey)){const source=cache.get(cacheKey),copy=document.createElement('canvas');copy.width=source.width;copy.height=source.height;copy.getContext('2d').drawImage(source,0,0);return copy}const page=await pdf.getPage(entry.source),viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(width);canvas.height=Math.ceil(entry.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport,transform:[1,0,0,1,entry.half===1?-width:0,0],background:'#fff'}).promise;cache.set(cacheKey,canvas);if(cache.size>32)cache.delete(cache.keys().next().value);const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;copy.getContext('2d').drawImage(canvas,0,0);return copy}
async function render(direction=0){if(!pdf||!pages.length)return;const token=++renderGeneration;const book=$('book'),n=count(),start=index;const stage=$('stage'),availableWidth=Math.max(100,stage.clientWidth-(innerWidth<=760?8:40)),availableHeight=Math.max(100,stage.clientHeight-(innerWidth<=760?16:40));const entries=pages.slice(start,start+n);const totalWidth=entries.reduce((sum,e)=>sum+e.width,0),height=Math.max(...entries.map(e=>e.height));const scale=Math.min(availableWidth/(n===2&&entries.length===1?entries[0].width*2:totalWidth),availableHeight/height)*zoom;const ratio=Math.min(devicePixelRatio||1,2);const canvases=await Promise.all(entries.map(async e=>{const c=await canvasFor(e,Math.min(2800,e.width*scale*ratio));c.style.width=`${e.width*scale}px`;c.style.height=`${e.height*scale}px`;return c}));if(token!==renderGeneration)return;let turning=curl;
if(direction&&$('animate').checked&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!turning)turning=createCurl(direction);
book.replaceChildren(...canvases);book.classList.toggle('double',n===2&&canvases.length===2);
if(turning){book.append(turning.canvas);await settleCurl(turning,1)}else if(direction){bookSound()}
await attachPageLinks(pdf,pages,entries,canvases,book,()=>token===renderGeneration,target=>{if(!busy&&performance.now()>=suppressClickUntil)go(target)});
$('pageInput').value=index+1;$('progress').value=index;$('bookInfo').textContent=`${index+1}${entries.length>1?'–'+(index+2):''} из ${pages.length} страниц`;$('prev').disabled=index===0;$('next').disabled=index+n>=pages.length;$('bookmark').textContent=marks.includes(index)?'★':'☆';$('wholeSpread').textContent=wholeSources.has(pages[index].source)?'Разделить этот разворот на страницы':'Показать этот разворот целиком';$('wholeSpread').disabled=pages[index].half===null&&!wholeSources.has(pages[index].source);document.querySelectorAll('.thumb').forEach(el=>el.classList.toggle('active',Number(el.dataset.page)===index));remember()}
async function go(target,direction=0){if(!pdf||busy||!Number.isFinite(target))return;busy=true;try{const next=Math.max(0,Math.min(pages.length-1,target));if(next===index){if(curl)await settleCurl(curl,0);return}index=next;await render(direction)}catch(e){console.error(e);toast('Ошибка отображения страницы')}finally{busy=false}}
async function sidebar(){thumbObserver?.disconnect();$('sideContent').replaceChildren();if(!pdf){$('sideContent').textContent='Откройте PDF, чтобы увидеть страницы.';return}const content=$('sideContent');if(tab==='pages'){const token=generation;thumbObserver=new IntersectionObserver(async records=>{for(const item of records){if(!item.isIntersecting)continue;thumbObserver.unobserve(item.target);const i=Number(item.target.dataset.page);try{const c=await canvasFor(pages[i],150);if(token===generation&&item.target.isConnected)item.target.prepend(c)}catch{}}},{root:content,rootMargin:'200px'});pages.forEach((e,i)=>{const b=document.createElement('button');b.className='thumb'+(i===index?' active':'');b.dataset.page=i;b.style.minHeight='110px';const label=document.createElement('span');label.textContent=`Страница ${i+1}${e.half!==null?' · '+(e.half===0?'левая':'правая')+' половина':''}`;b.append(label);b.onclick=()=>go(i);content.append(b);thumbObserver.observe(b)})}else if(tab==='marks'){if(!marks.length)content.textContent='Нажмите ☆, чтобы сохранить страницу.';marks.slice().sort((a,b)=>a-b).forEach(i=>{const row=document.createElement('div'),b=document.createElement('button'),remove=document.createElement('button');b.textContent=`Страница ${i+1}`;b.onclick=()=>go(i);remove.textContent='×';remove.title='Удалить закладку';remove.onclick=()=>{marks=marks.filter(m=>m!==i);remember();sidebar();render()};row.append(b,remove);content.append(row)})}else{const input=document.createElement('input');input.className='search-input';input.placeholder='Найти в книге…';input.setAttribute('aria-label','Поиск по тексту');const results=document.createElement('div');content.append(input,results);let timer;input.oninput=()=>{clearTimeout(timer);++searchGeneration;timer=setTimeout(()=>search(input.value,results),350)};input.focus();const note=document.createElement('p');note.textContent='Для сканов без текстового слоя поиск недоступен.';note.style.color='var(--muted)';note.style.fontSize='11px';content.append(note)}}
async function search(query,results){const token=++searchGeneration,doc=pdf;results.replaceChildren();if(!query.trim())return;results.textContent='Ищем…';const found=[];for(let p=1;p<=doc.numPages;p++){const data=await(await doc.getPage(p)).getTextContent();if(token!==searchGeneration||doc!==pdf)return;const matching=data.items.filter(t=>t.str?.toLocaleLowerCase().includes(query.toLocaleLowerCase()));for(const match of matching){const page=await doc.getPage(p),v=page.getViewport({scale:1}),point=v.convertToViewportPoint(match.transform[4],match.transform[5]);const i=pages.findIndex(e=>e.source===p&&(e.half===null||e.half===(point[0]>=v.width/2?1:0)));found.push({i,text:match.str})}}if(token!==searchGeneration)return;results.replaceChildren();if(!found.length)results.textContent='Совпадений не найдено';found.slice(0,200).forEach(hit=>{const b=document.createElement('button');b.className='result';b.textContent=`Стр. ${hit.i+1} · ${hit.text}`;b.onclick=()=>go(hit.i);results.append(b)})}
function download(data,filename,type='application/pdf'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('open').onclick=$('welcomeOpen').onclick=()=>$('file').click();$('file').onchange=async e=>{await fileOpen(e.target.files[0]);e.target.value=''};
$('demo').onclick=async()=>{try{loading(true);const res=await fetch('./JAVA тілінде оьбектіге-бағытталған бағдарламалау1.pdf');if(!res.ok)throw Error();await openPDF(new Uint8Array(await res.arrayBuffer()),'JAVA тілінде объектіге-бағытталған бағдарламалау.pdf')}catch{loading(false);toast('Книга из проекта недоступна. Выберите свой PDF.')}};
$('prev').onclick=()=>go(index-count(),-1);$('next').onclick=()=>go(index+count(),1);$('first').onclick=()=>go(0,-1);$('last').onclick=()=>go(pages.length-1,1);$('pageInput').onchange=e=>go(Number(e.target.value)-1);$('progress').oninput=e=>go(Number(e.target.value));
$('sidebar').classList.add('collapsed');$('sideToggle').onclick=()=>{$('sidebar').classList.toggle('collapsed');requestAnimationFrame(()=>render())};$('closeSide').onclick=()=>{$('sidebar').classList.add('collapsed');render()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;++searchGeneration;document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));sidebar()});
$('bookmark').onclick=()=>{if(!pdf)return;marks=marks.includes(index)?marks.filter(m=>m!==index):[...marks,index];remember();render();if(tab==='marks')sidebar()};
$('theme').onclick=()=>{document.body.classList.toggle('dark');safeStore.set('list:dark',document.body.classList.contains('dark'))};document.body.classList.toggle('dark',safeStore.get('list:dark',false));
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Полноэкранный режим недоступен')}};
$('settingsToggle').onclick=()=>$('settings').hidden=!$('settings').hidden;
$('view').onchange=()=>render();$('split').onchange=async()=>{if(!pdf)return;loading(true,'Разделяем страницы…');try{++searchGeneration;await rebuild();await render();await sidebar();toast(`Готово: ${pages.length} страниц`)}catch(e){toast('Не удалось разделить PDF')}finally{loading(false)}};
function setZoom(value){zoom=Math.min(3,Math.max(.5,value));document.body.classList.toggle('zoomed',zoom!==1);$('zoomReset').textContent=Math.round(zoom*100)+'%';render()}$('zoomIn').onclick=()=>setZoom(zoom+.25);$('zoomOut').onclick=()=>setZoom(zoom-.25);$('zoomReset').onclick=()=>setZoom(1);
$('download').onclick=()=>bytes?download(bytes,name):toast('Сначала откройте PDF');
$('export').onclick=async()=>{if(!pdf)return toast('Сначала откройте PDF');loading(true,'Создаём PDF с отдельными страницами…');try{const {PDFDocument,degrees}=PDFLib,src=await PDFDocument.load(bytes),out=await PDFDocument.create();const copied=await out.copyPages(src,pages.map(e=>e.source-1));for(const [pageIndex,entry] of pages.entries()){const page=copied[pageIndex];const box=page.getCropBox(),rotation=((page.getRotation().angle%360)+360)%360;if(entry.half!==null){let{x,y,width,height}=box;if(rotation===90||rotation===270){height/=2;y+=(rotation===90?entry.half===1:entry.half===0)?height:0}else{width/=2;x+=(rotation===180?1-entry.half:entry.half)*width}page.setMediaBox(x,y,width,height);page.setCropBox(x,y,width,height)}out.addPage(page)}download(await out.save(),name.replace(/\.pdf$/i,'')+' — отдельные страницы.pdf');toast('Разделённый PDF сохранён')}catch(e){console.error(e);toast('Не удалось сохранить PDF. Для защищённых файлов экспорт может быть недоступен.')}finally{loading(false)}};
$('print').onclick=()=>{if(!bytes)return toast('Сначала откройте PDF');const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));const win=window.open(url);if(!win)toast('Разрешите всплывающее окно для печати');else win.onload=()=>win.print();setTimeout(()=>URL.revokeObjectURL(url),120000)};
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();go(index+count(),1)}if(e.key==='ArrowLeft'){e.preventDefault();go(index-count(),-1)}if(e.key.toLowerCase()==='f')$('fullscreen').click();if(e.key==='+'||e.key==='=')setZoom(zoom+.25);if(e.key==='-')setZoom(zoom-.25);if(e.key==='Escape'){$('settings').hidden=true;$('sidebar').classList.add('collapsed');render()}});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>render(),160)});
// Pointer gestures distinguish horizontal page turns from scrolling and zoomed panning.
$('stage').addEventListener('pointerdown',e=>{if(!pdf||busy||zoom!==1||e.pointerType==='mouse'&&e.button!==0)return;if(gesture){cancelGesture();return}gesture={id:e.pointerId,x:e.clientX,y:e.clientY,time:performance.now(),direction:0};});
$('stage').addEventListener('pointermove',e=>{if(!gesture||gesture.id!==e.pointerId)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(!gesture.direction){if(Math.abs(dy)>12&&Math.abs(dy)>Math.abs(dx)){gesture=null;return}if(Math.abs(dx)<10||Math.abs(dx)<Math.abs(dy)*1.2)return;const direction=dx<0?1:-1;if(direction>0&&index+count()>=pages.length||direction<0&&index===0){gesture=null;return}gesture.direction=direction;$('stage').setPointerCapture(e.pointerId);if($('animate').checked&&!matchMedia('(prefers-reduced-motion: reduce)').matches)curl=createCurl(direction);}if(gesture.direction){e.preventDefault();gesture.distance=Math.max(0,dx*-gesture.direction);if(curl){curl.dragY=Math.max(-.4,Math.min(.4,dy/curl.height));drawCurl(curl,Math.min(.88,gesture.distance/curl.width));}}});
$('stage').addEventListener('pointerup',e=>{if(!gesture||gesture.id!==e.pointerId)return;const current=gesture;gesture=null;if(!current.direction)return;suppressClickUntil=performance.now()+600;const elapsed=performance.now()-current.time,distance=current.distance||0;if(distance>Math.min(90,$('stage').clientWidth*.22)||distance>28&&distance/elapsed>.35)go(index+current.direction*count(),current.direction);else if(curl)cancelGesture();});
async function cancelGesture(){gesture=null;if(curl){busy=true;try{await settleCurl(curl,0)}finally{busy=false}}}
$('stage').addEventListener('pointercancel',cancelGesture);
let dragDepth=0;window.addEventListener('dragenter',e=>{e.preventDefault();if(e.dataTransfer.types.includes('Files')){dragDepth++;document.body.classList.add('drag')}});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('dragleave',()=>{if(--dragDepth<=0)document.body.classList.remove('drag')});window.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;document.body.classList.remove('drag');fileOpen(e.dataTransfer.files[0])});
$('book').addEventListener('click',e=>{if(e.target.closest('.pdf-link'))return;if(innerWidth<=760||performance.now()<suppressClickUntil||zoom!==1||busy)return;const box=$('book').getBoundingClientRect(),x=e.clientX-box.left;if(x<box.width*.2)go(index-count(),-1);else if(x>box.width*.8)go(index+count(),1)});
sidebar();

$('changeFile').onclick=()=>{$('settings').hidden=true;$('file').click()};
$('wholeSpread').onclick=async()=>{if(!pdf)return;const source=pages[index].source,wasWhole=wholeSources.has(source);const marked=marks.map(i=>pages[i]).filter(Boolean);if(wasWhole)wholeSources.delete(source);else wholeSources.add(source);loading(true,'Обновляем разворот…');try{await rebuild();index=pages.findIndex(e=>e.source===source);marks=marked.map(m=>pages.findIndex(e=>e.source===m.source&&(m.half===null||e.half===m.half||e.half===null))).filter(i=>i>=0);await render();await sidebar();$('settings').hidden=true;toast(wasWhole?'Разворот разделён на страницы':'Этот разворот сохранён целиком')}finally{loading(false)}};

$('sound').checked=safeStore.get('list:sound',true);
function unlockPageSound(){if($('sound').checked)preparePageSound()}
document.addEventListener('pointerdown',unlockPageSound,{passive:true});
document.addEventListener('keydown',unlockPageSound);
$('sound').addEventListener('change',()=>{safeStore.set('list:sound',$('sound').checked);unlockPageSound()});
